spring.application.name=allra

spring.datasource.url=jdbc:mysql://localhost:3306/cart_order?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
spring.datasource.username=nbs_dev
spring.datasource.password=nbsdev1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

payment.api.base-url=https://allra.free.beeceptor.com
payment.api.path=/api/v1/payment